import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — Munch Snapper',
};

const COLOURS = {
  magenta: '#B0185E',
  nearBlack: '#0E0E10',
  card: '#1a1a1e',
  border: '#2a2a30',
  white: '#ffffff',
  textMuted: 'rgba(255,255,255,0.75)',
  textFaint: 'rgba(255,255,255,0.5)',
};

const SECTIONS: Array<{ title: string; body: React.ReactNode }> = [
  {
    title: '1. Acceptance of terms',
    body: 'By creating an account or using Munch Snapper, you agree to these terms. If you do not agree, do not use the service.',
  },
  {
    title: '2. What Munch Snapper provides',
    body: 'Munch Snapper is a nutrition tracking tool that uses AI to estimate the calorie and macro content of meals from photos, barcodes, voice descriptions, and text. It also provides habit tracking, an AI coaching assistant, and pre-built meal plan guidance.',
  },
  {
    title: '3. Not medical advice',
    body: 'Munch Snapper is not a medical device and does not provide medical advice, diagnosis, or treatment. Calorie and macro estimates are approximations based on AI analysis and should not be relied upon for medical, clinical, or therapeutic purposes. Always consult a qualified healthcare professional before making significant changes to your diet.',
  },
  {
    title: '4. Account responsibility',
    body: 'You are responsible for keeping your login credentials secure. You must be at least 16 years old to create an account. You must provide accurate information when setting up your account.',
  },
  {
    title: '5. Subscription and billing',
    body: 'Munch Snapper offers a monthly subscription at £5.99/month and an annual subscription at £49.99/year. New users receive 3 free photo analyses before payment is required. Monthly subscribers may cancel at any time. Annual subscribers may cancel before the renewal date. No refunds are issued for partial billing periods. Payments are processed by Stripe.',
  },
  {
    title: '6. Acceptable use',
    body: 'You agree not to use Munch Snapper to: violate any applicable law, attempt to reverse-engineer the AI or application, scrape or extract data from the service, or misuse the platform in any way that could harm other users or the service itself.',
  },
  {
    title: '7. AI-generated content',
    body: "The coaching notes and AI Coach responses are generated by large language models. While Stacy Kundu's voice and coaching philosophy inform these outputs, they are AI-generated and should be understood as general guidance, not personalised professional advice.",
  },
  {
    title: '8. Intellectual property',
    body: 'All content, branding, and code within Munch Snapper is the property of Stacy Kundu and Munch Snapper. You may not reproduce, copy, or redistribute any part of the service without written permission.',
  },
  {
    title: '9. Limitation of liability',
    body: 'To the fullest extent permitted by law, Munch Snapper and Stacy Kundu shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.',
  },
  {
    title: '10. Changes to these terms',
    body: 'We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the updated terms.',
  },
  {
    title: '11. Governing law',
    body: 'These terms are governed by the laws of England and Wales.',
  },
  {
    title: '12. Contact',
    body: (
      <>
        For any questions about these terms:{' '}
        <a
          href="mailto:help@munchsnapper.com"
          style={{ color: COLOURS.magenta, textDecoration: 'none', fontWeight: 600 }}
        >
          help@munchsnapper.com
        </a>
      </>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <main
      style={{
        minHeight: '100vh',
        background: COLOURS.nearBlack,
        color: COLOURS.white,
        fontFamily: "'Barlow', sans-serif",
        padding: '2.5rem 1.25rem 4rem',
        display: 'flex',
        justifyContent: 'center',
      }}
    >
      <div
        style={{
          width: '100%',
          maxWidth: 720,
          display: 'flex',
          flexDirection: 'column',
          gap: '1.75rem',
        }}
      >
        <Link
          href="/"
          style={{
            color: COLOURS.textMuted,
            textDecoration: 'none',
            fontSize: 13,
            letterSpacing: '0.02em',
          }}
        >
          ← Back to Munch Snapper
        </Link>

        <header style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <span
            style={{
              fontSize: 11,
              fontWeight: 600,
              letterSpacing: '0.14em',
              textTransform: 'uppercase',
              color: COLOURS.magenta,
            }}
          >
            Munch Snapper
          </span>
          <h1
            style={{
              fontFamily: "'Barlow Condensed', sans-serif",
              fontWeight: 800,
              fontSize: 'clamp(2rem, 5vw, 3rem)',
              lineHeight: 1.05,
              margin: 0,
              letterSpacing: '-0.01em',
            }}
          >
            Terms of Service
          </h1>
          <div style={{ fontSize: 13, color: COLOURS.textFaint }}>Last updated: June 2026</div>
        </header>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {SECTIONS.map((s) => (
            <section
              key={s.title}
              style={{
                background: COLOURS.card,
                border: `1px solid ${COLOURS.border}`,
                borderRadius: 14,
                padding: '18px 20px',
                display: 'flex',
                flexDirection: 'column',
                gap: 10,
              }}
            >
              <h2
                style={{
                  fontFamily: "'Barlow Condensed', sans-serif",
                  fontWeight: 800,
                  fontSize: 20,
                  lineHeight: 1.15,
                  color: COLOURS.magenta,
                  margin: 0,
                  letterSpacing: '-0.01em',
                }}
              >
                {s.title}
              </h2>
              <div
                style={{
                  fontSize: 14.5,
                  lineHeight: 1.65,
                  color: COLOURS.textMuted,
                }}
              >
                {s.body}
              </div>
            </section>
          ))}
        </div>

        <Link
          href="/"
          style={{
            color: COLOURS.textMuted,
            textDecoration: 'none',
            fontSize: 13,
            letterSpacing: '0.02em',
            alignSelf: 'flex-start',
          }}
        >
          ← Back to Munch Snapper
        </Link>
      </div>
    </main>
  );
}
